name: 'CI-test'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    #    runs-on: macos-latest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .gradle
            .kotlin
          key: ${{ runner.os }}-primes

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check -i

      - name: Make Kover report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: koverHtmlReport

      - name: View application line coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: koverPrintCoverage

      - name: Upload Kover report
        uses: actions/upload-artifact@v4
        with:
          name: kover-report
          path: build/reports/kover/html

      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            .gradle
            .kotlin
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
